import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "../components/Card/Card";
import axios from "axios";
import useFetch from "../hooks/useFetch";

function Home() {
  const { data, loading, error } = useFetch(
    "https://pokeapi.co/api/v2/pokemon?limit=10&offset=0"
  );

  if (error) {
    // show alert
    console.log(error);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {loading && (
          <div>
            <h1 className={styles.title}>Cargando</h1>
          </div>
        )}
        {data && (
          <div className={styles.grid}>
            <h1 className={styles.title}>Contratenme porfis</h1>
            {data.results.map((pokemon, index) => (
              <Card key={index} title={pokemon.name} body="hola" />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}

export default Home;
