import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "../components/Card/Card";
import axios from "axios";
import color from "../styles/color";

function Home() {
  const [data, setData] = useState("");

  useEffect(() => {
    const getData = async () => {
      try {
        const response = await axios.get(
          "https://api.chucknorris.io/jokes/random"
        );
        setData(response.data);
      } catch (error) {
        console.log("error");
      }
    };
    getData();
  }, []);

  const submitData = () => {
    const getData = async () => {
      try {
        const response = await axios.get(
          "https://api.chucknorris.io/jokes/random"
        );
        setData(response.data);
      } catch (error) {
        console.log("error");
      }
    };
    getData();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data && (
        <main className={styles.main}>
          <Card title="Broma del día jaja" body={data.value} />
          <button
            type="button"
            onClick={submitData}
            style={{
              backgroundColor: color.blue[200],
              width: "300px",
              height: "30px",
            }}
          >
            Click Me
          </button>
        </main>
      )}
    </div>
  );
}

export default Home;
