import Head from "next/head";
import styles from "../styles/Home.module.css";
import Card from "../components/Card/Card";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Contratenme porfis</h1>

        <div className={styles.grid}>
          <Card title="hola" body="body" />
          <Card title="hola" body="body" />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </main>
    </div>
  );
}
